# Generated by Django 2.1.7 on 2019-03-30 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0002_auto_20190330_1803'),
        ('main', '0002_auto_20190330_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('1', 'Волонтер'), ('2', 'Организатор'), ('3', 'Администратор')], max_length=1, verbose_name='Уровень задачи')),
                ('title', models.TextField(max_length=256, verbose_name='Заголовок задачи')),
                ('description', models.TextField(max_length=1024, verbose_name='Бодробное описание задачи')),
                ('status', models.CharField(choices=[('1', 'открыто'), ('2', 'в работе'), ('3', 'проверка'), ('4', 'закрыто')], default='1', max_length=1, verbose_name='Статус задачи')),
                ('need_performers', models.BooleanField(default=False, verbose_name='Задача открыта для исполнителей')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Дата создания задачи')),
                ('deadline', models.DateTimeField(verbose_name='Дэдлайн задачи')),
                ('priority', models.CharField(choices=[('1', 'высокий'), ('2', 'средний'), ('3', 'низкий')], max_length=1, verbose_name='Приоритет задачи')),
                ('tags', models.CharField(max_length=128, verbose_name='Тэги задачи')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author', to='main.UserProfile', verbose_name='Автор задачи')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event', verbose_name='Для мероприятия')),
                ('task_performers', models.ManyToManyField(related_name='task_performers', to='main.UserProfile', verbose_name='Исполнители задачи')),
            ],
        ),
    ]
