# Generated by Django 2.1.7 on 2019-03-30 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20190330_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(max_length=1024, verbose_name='Подробное описание задачи'),
        ),
        migrations.AlterField(
            model_name='task',
            name='level',
            field=models.CharField(choices=[('volunteer', 'Волонтер'), ('arganizer', 'Организатор'), ('admin', 'Администратор')], max_length=9, verbose_name='Уровень задачи'),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('high', 'высокий'), ('medium', 'средний'), ('low', 'низкий')], max_length=6, verbose_name='Приоритет задачи'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('open', 'открыто'), ('inProgress', 'в работе'), ('check', 'проверка'), ('close', 'закрыто')], default='10', max_length=1, verbose_name='Статус задачи'),
        ),
        migrations.AlterField(
            model_name='task',
            name='tags',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Тэги задачи'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Заголовок задачи'),
        ),
    ]
