# Generated by Django 2.1.7 on 2019-03-30 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20190331_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('open', 'открыто'), ('inProgress', 'в работе'), ('check', 'проверка'), ('close', 'закрыто')], default='open', max_length=10, verbose_name='Статус задачи'),
        ),
    ]
