# Generated by Django 2.1.7 on 2019-03-30 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20190331_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='events.Event', verbose_name='Для мероприятия'),
        ),
        migrations.AlterField(
            model_name='task',
            name='level',
            field=models.CharField(choices=[('volunteer', 'Волонтер'), ('organizer', 'Организатор'), ('admin', 'Администратор')], max_length=9, verbose_name='Уровень задачи'),
        ),
    ]
