# Generated by Django 2.1.7 on 2019-03-31 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_auto_20190331_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_performers',
            field=models.ManyToManyField(blank=True, related_name='task_performers', to='main.UserProfile', verbose_name='Исполнители задачи'),
        ),
    ]
