# Generated by Django 2.1.7 on 2019-03-31 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_auto_20190331_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Подробное описание задачи'),
        ),
    ]
