# Generated by Django 2.1.7 on 2019-03-31 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_auto_20190331_0650'),
        ('tasks', '0008_auto_20190331_0707'),
    ]

    operations = [
    ]
