# Generated by Django 2.1.7 on 2019-03-31 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_auto_20190331_0803'),
        ('tasks', '0009_merge_20190331_0756'),
    ]

    operations = [
    ]
