# Generated by Django 2.1.7 on 2019-03-30 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0002_auto_20190330_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название мероприятия')),
                ('slug', models.CharField(max_length=128, verbose_name='Короткое название, метка')),
                ('short_description', models.TextField(max_length=256, verbose_name='Краткое описание мероприятия')),
                ('description', models.TextField(max_length=1024, verbose_name='Развернутое описание мероприятия')),
                ('date', models.DateField(verbose_name='Дата проведения мероприятия')),
                ('time_start', models.TimeField(verbose_name='Время начала мероприятия')),
                ('time_end', models.TimeField(verbose_name='Время окончания мероприятия')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='events', verbose_name='Фото или лого мероприятия')),
                ('partners', models.ManyToManyField(to='main.Partner')),
                ('responsible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.UserProfile')),
            ],
        ),
    ]
