# Generated by Django 2.1.7 on 2019-03-30 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, default='', max_length=1024, verbose_name='Развернутое описание мероприятия'),
        ),
        migrations.AlterField(
            model_name='event',
            name='partners',
            field=models.ManyToManyField(to='main.Partner', verbose_name='Партнеры мероприятия'),
        ),
        migrations.AlterField(
            model_name='event',
            name='responsible',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.UserProfile', verbose_name='Ответственный за мероприятие'),
        ),
    ]
