# Generated by Django 2.1.7 on 2019-03-30 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20190330_1803'),
        ('events', '0002_auto_20190330_1710'),
    ]

    operations = [
    ]
