# Generated by Django 2.1.7 on 2019-03-30 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_merge_20190330_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.CharField(max_length=128, unique=True, verbose_name='Короткое название, метка'),
        ),
    ]
