# Generated by Django 2.1.7 on 2019-03-30 12:49

from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteractionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_link', models.CharField(choices=[('1', 'Email'), ('2', 'Телефон'), ('3', 'Личная встреча')], max_length=1, verbose_name='Канал связи')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время взамодействия')),
                ('about', models.TextField(max_length=1024, verbose_name='По какому вопросу')),
                ('result', models.TextField(max_length=256, verbose_name='Результат взаимодействия')),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('1', 'Юридическое лицо'), ('2', 'Физическое лицо')], max_length=1, verbose_name='Статус партнера')),
                ('name', models.CharField(max_length=128, verbose_name='Название организации или ФИО физ.лица')),
                ('tin', models.UUIDField(blank=True, null=True, verbose_name='Идентификационный номер налогоплательщика')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Веб-сайт')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')], verbose_name='Номер телефона')),
                ('short_description', models.TextField(max_length=256, verbose_name='Краткое описание')),
                ('description', models.TextField(blank=True, max_length=1024, null=True, verbose_name='Полное описание')),
                ('contact_name', models.CharField(max_length=128, verbose_name='ФИО контактного лица')),
                ('contact_phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')], verbose_name='Номер контактного телефона')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Контактный Email')),
                ('communication_method', models.CharField(choices=[('1', 'Email'), ('2', 'Телефон'), ('3', 'Личная встреча')], default='1', max_length=1, verbose_name='Предпочтительный способ связи')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('short_description', models.TextField(max_length=256, verbose_name='Краткое описание')),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')], verbose_name='Номер телефона')),
                ('role', models.CharField(choices=[('1', 'Волонтер'), ('2', 'Организатор'), ('3', 'Администратор')], max_length=1, verbose_name='Статус пользователя')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='interactionhistory',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Partner', verbose_name='Партнер'),
        ),
    ]
