# Generated by Django 2.1.7 on 2019-03-30 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='partners', verbose_name='Фото или лого партнера'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='users', verbose_name='Фотография'),
        ),
    ]
