# Generated by Django 2.1.7 on 2019-03-30 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190330_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='slug',
            field=models.CharField(default='partner1', max_length=128, unique=True, verbose_name='Короткое название, метка'),
            preserve_default=False,
        ),
    ]
