# Generated by Django 2.1.7 on 2019-03-30 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_partner_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='tags',
            field=models.CharField(default='', max_length=128, verbose_name='Тэги'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('volunteer', 'Волонтер'), ('arganizer', 'Организатор'), ('admin', 'Администратор')], max_length=9, verbose_name='Статус пользователя'),
        ),
    ]
