# Generated by Django 2.1.7 on 2019-03-30 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20190331_0101'),
        ('main', '0005_auto_20190330_2232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='tags',
        ),
        migrations.AddField(
            model_name='partner',
            name='tags',
            field=models.ManyToManyField(related_name='partner', to='tasks.Tag', verbose_name='Тэги'),
        ),
    ]
