# Generated by Django 2.1.7 on 2019-03-30 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190331_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='partner', to='tasks.Tag', verbose_name='Тэги'),
        ),
    ]
