# Generated by Django 2.1.7 on 2019-03-30 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190331_0101'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('volunteer', 'Волонтер'), ('organizer', 'Организатор'), ('admin', 'Администратор')], max_length=9, verbose_name='Статус пользователя'),
        ),
    ]
