# Generated by Django 2.1.7 on 2019-03-31 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20190331_0650'),
        ('main', '0010_auto_20190331_0803'),
    ]

    operations = [
    ]
