# Generated by Django 2.1.7 on 2019-03-31 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20190331_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interactionhistory',
            name='interaction_link',
            field=models.CharField(choices=[('email', 'Email'), ('phone', 'Телефон'), ('meet', 'Личная встреча')], max_length=10, verbose_name='Канал связи'),
        ),
    ]
