# Generated by Django 2.1.7 on 2019-03-31 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20190331_0929'),
        ('main', '0012_auto_20190331_0920'),
    ]

    operations = [
    ]
